#pragma once

#include <DearModdingUI/Client.h>

namespace cs::host
{
	inline constexpr dmui::ClientOptions kClientOptions{
		.capabilities = DMUI_CLIENT_CAPABILITY_RENDERER_REPLACEMENT,
		.requiredServices =
			DMUI_HOST_SERVICE_FRAME_CONTROL |
			DMUI_HOST_SERVICE_EDIT_LIFECYCLE |
			DMUI_HOST_SERVICE_CONTEXTUAL_HOTKEYS |
			DMUI_HOST_SERVICE_IMAGE_RESOURCES |
			DMUI_HOST_SERVICE_MANAGED_OVERLAYS |
			DMUI_HOST_SERVICE_NOTIFICATIONS |
			DMUI_HOST_SERVICE_ANNOTATED_PLOTS |
			DMUI_HOST_SERVICE_DIALOGS |
			DMUI_HOST_SERVICE_EXTERNAL_OPEN,
		.minimumForwardingVersion = DMUI_FORWARDING_VERSION_1_1
	};
}
