void AppendPrepassLodShaderReplacementVariants(
	std::vector<ShaderReplacementVariantRegistration>& a_variants)
{
	using Target = ShaderInjectionTarget;
	const auto append = [&a_variants](
		std::string a_name,
		std::string a_expectedStockSha1,
		ShaderInjectionDefines a_defines,
		ShaderStage a_stage,
		std::wstring a_sourcePath) {
		auto registration = MakeDefaultVariantRegistration(
			Target::kDeferredPrepass,
			std::move(a_name),
			{},
			std::move(a_expectedStockSha1),
			std::move(a_defines),
			a_stage);
		registration.compilation.sourcePath = std::move(a_sourcePath);
		a_variants.push_back(std::move(registration));
	};

	a_variants.reserve(a_variants.size() + 31);
	append(
		"bsdfprepass_lod_landscape_ps2661",
		"47bbe0535307a6a4beff5ab62050b25494bd9cd8",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "1" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2659",
		"50ff21d4e407b11b80453d3c5705ab5f7502b61b",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "1" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2867",
		"5d7c23fe276a3d182bf0985cfcbc2bf9a02d8278",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2658",
		"6220551a5773b6a11bda8e32b88ed266b43f4efd",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "1" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2800",
		"65918f5834edafabb6199d073625d1a6f5e4468e",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2860",
		"6d031b8b738440db218bc25621799aeaeb459ccc",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2854",
		"84063fc0865832aed8ad1a5d7a12a876a41b2b7b",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "1" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2612",
		"8cf781a7370c67efb8c44a17a05a5a8b5423faaa",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "1" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2613",
		"a7ec9a783e5608fc40d391573be5316b059e92b7",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "1" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2868",
		"b6b0b5b52a2d6c70e2915abe3a28ae39b54e96c5",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps3013",
		"bc3c8f53a049ec00c778852e8984210730e71c26",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "1" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2949",
		"c30bde346dfc1520b9c6c2635c3d9c85d46f2028",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "1" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2828",
		"c5578ced20e3b2909bd7089ab420103813e1bd13",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "1" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_ps2853",
		"e99f1c5af81889ebcfec308efb95400c452cce4e",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "1" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_land_lod_blend_ps2858",
		"1dcf7cfc9509e2990127abfb5a665f57b0217b84",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "1" },
			{ "LAND_LOD_BLEND", "1" },
			{ "LOD_LANDSCAPE", "0" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "PIPBOY_SCREEN", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "TREE_ANIM", "0" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_land_lod_blend_ps2680",
		"e3c03ae9c5ca1f6855215cee706b582e261b258f",
		{
			{ "ADDITIONAL_ALPHA_MASK", "0" },
			{ "ALPHA_TEST", "0" },
			{ "BLEND", "0" },
			{ "BONE_TINTING", "0" },
			{ "EARLYDEPTH", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GLOWMAP", "0" },
			{ "GRADIENT_REMAP", "0" },
			{ "HAIR", "0" },
			{ "INSTANCED", "1" },
			{ "LANDSCAPE", "1" },
			{ "LAND_LOD_BLEND", "1" },
			{ "LOD_LANDSCAPE", "0" },
			{ "MENU_SCREEN", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "PIPBOY_SCREEN", "0" },
			{ "SKEW_SPECULAR_ALPHA", "0" },
			{ "SKIN_TINT", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "TREE_ANIM", "0" },
			{ "VC", "1" }
		},
		ShaderStage::kPixel,
		L"BSDFPrePass.hlsl");
	append(
		"bsdfprepass_lod_landscape_vs2317",
		"1266a115a561eaa03756b043f872c9f93f86679a",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "0" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2320",
		"196aa6ba9a03c455a48f8605def35d262f40889d",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "EYE", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "1" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2375",
		"49394e22917211b03b34fefaf17f5ea6f3aeac5e",
		{
			{ "BINORMAL_TANGENT", "0" },
			{ "BONE_TINTING", "0" },
			{ "CLIP_VOLUME", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GRASS", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "LOD_OBJECT_INSTANCED", "0" },
			{ "MERGE_INSTANCED", "0" },
			{ "MODELSPACENORMALS", "1" },
			{ "NORMALS", "0" },
			{ "PIPBOY_SCREEN", "0" },
			{ "SKINNED", "0" },
			{ "SPLINE", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "TREE_ANIM", "0" },
			{ "VC", "0" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2153",
		"55bf7c83fe8bf602d018a8bd7e8528cea628b391",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2152",
		"565ee87d074fe45128bb39057b6f5453fd691f5a",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2178",
		"58eb23f666413a729c669e03400aef29317681b4",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "EYE", "0" },
			{ "INSTANCED", "1" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2179",
		"5df0a3f156bcc40fcf663814acff0583c60d0b9a",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "EYE", "0" },
			{ "INSTANCED", "1" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2316",
		"68afc38cbcf0e8328e9a6e152d658288f38e8c85",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "0" },
			{ "CLIP_VOLUME", "0" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GRASS", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "1" },
			{ "LOD_LANDSCAPE", "1" },
			{ "LOD_OBJECT_INSTANCED", "0" },
			{ "MERGE_INSTANCED", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "PIPBOY_SCREEN", "0" },
			{ "SKINNED", "0" },
			{ "SPLINE", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "TREE_ANIM", "0" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2180",
		"76441d60498272cc31e995a68a1a06d26d5addc0",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "EYE", "0" },
			{ "INSTANCED", "1" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "1" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2319",
		"7edfdd378b047f14974f878337945cb3241a3771",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "EYE", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "1" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2318",
		"a41e1a51335574860b2434e43141bcff78cdb46b",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "0" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "SKINNED", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_landscape_vs2459",
		"d31123109ae985acb91ab15e012d53ee0e62fac3",
		{
			{ "BINORMAL_TANGENT", "0" },
			{ "BONE_TINTING", "0" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "MODELSPACENORMALS", "1" },
			{ "NORMALS", "0" },
			{ "SKINNED", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "VC", "0" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodLandscapeVertex.hlsli");
	append(
		"bsdfprepass_lod_object_vs2266",
		"934c836603ddbf954bc00cc079bb1b10cb2aba47",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "0" },
			{ "CLIP_VOLUME", "0" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GRASS", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "0" },
			{ "LOD_OBJECT_INSTANCED", "1" },
			{ "MERGE_INSTANCED", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "PIPBOY_SCREEN", "0" },
			{ "SKINNED", "0" },
			{ "SPLINE", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "TREE_ANIM", "0" },
			{ "VC", "0" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodObjectInstancedVS.hlsli");
	append(
		"bsdfprepass_lod_object_vs2272",
		"58a5f6bed118be652be960dd27b6b5d891d0b11c",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "0" },
			{ "CLIP_VOLUME", "0" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GRASS", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "LOD_OBJECT_INSTANCED", "1" },
			{ "MERGE_INSTANCED", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "PIPBOY_SCREEN", "0" },
			{ "SKINNED", "1" },
			{ "SPLINE", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "TREE_ANIM", "0" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodObjectInstancedVS.hlsli");
	append(
		"bsdfprepass_lod_object_vs2271",
		"5400fb402aec5cd384948b38629d8f2981f9f3fa",
		{
			{ "BINORMAL_TANGENT", "1" },
			{ "BONE_TINTING", "0" },
			{ "CLIP_VOLUME", "0" },
			{ "COMBINED", "0" },
			{ "DISMEMBERMENT", "0" },
			{ "DISMEMBERMENT_MEATCUFF", "0" },
			{ "EYE", "0" },
			{ "FACE", "0" },
			{ "GRASS", "0" },
			{ "INSTANCED", "0" },
			{ "LANDSCAPE", "0" },
			{ "LOD_LANDSCAPE", "1" },
			{ "LOD_OBJECT_INSTANCED", "1" },
			{ "MERGE_INSTANCED", "0" },
			{ "MODELSPACENORMALS", "0" },
			{ "NORMALS", "1" },
			{ "PIPBOY_SCREEN", "0" },
			{ "SKINNED", "0" },
			{ "SPLINE", "0" },
			{ "TESSELLATE_DISP_HEIGHT", "0" },
			{ "TEXTURE", "1" },
			{ "TREE_ANIM", "0" },
			{ "VC", "1" }
		},
		ShaderStage::kVertex,
		L"BSDFPrePass\\LodObjectInstancedVS.hlsli");
}
