#pragma once
// Generated by harness/shaders/generate-static-family-consumer-registrations.ps1; do not hand-edit.
// Producer compile flags: vs_5_0 /E main /Ges /O3.
// Non-representative vertex aliases verified byte-identical to their representative row.
// Additive pixel-registration compiled output: 17,891 bytes.
// Source SHA-256 BSSkyShader.hlsl: 2249542297cbd5e2ffd5dc86a31780daa43e9eadea438f531d65963d34df9bbe
// Source SHA-256 BSWaterShader.hlsl: 8bdb60224f4771557a3f4d22be3ed95e3ba77669d025c27b0d165b2d302ed50f
// Source SHA-256 BSLightingShader.hlsl: 918f411acbab0c6fbdb528b79cb01fadd74ddbfaab4ce5ee27a849c01dce21b3

#include "Render/ShaderInjection.h"

#include <vector>

namespace cs::engine
{
	void AppendStaticFamilyShaderReplacementVariants(
		std::vector<ShaderReplacementVariantRegistration>& a_variants);
}
