function(add_shader_stage TARGET_NAME)
	cmake_parse_arguments(
		PARSE_ARGV 1
		SHADER_STAGE
		""
		"DESTINATION"
		"DIRECTORIES;FILES"
	)

	if(NOT SHADER_STAGE_DESTINATION)
		message(FATAL_ERROR "add_shader_stage requires DESTINATION")
	endif()

	set(SHADER_STAGE_CONFIG
		"${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.cmake")
	file(WRITE "${SHADER_STAGE_CONFIG}"
		"set(SHADER_STAGE_DESTINATION [==[${SHADER_STAGE_DESTINATION}]==])\n")
	foreach(SOURCE_DIRECTORY IN LISTS SHADER_STAGE_DIRECTORIES)
		file(APPEND "${SHADER_STAGE_CONFIG}"
			"list(APPEND SHADER_STAGE_DIRECTORIES [==[${SOURCE_DIRECTORY}]==])\n")
	endforeach()
	foreach(SOURCE_FILE IN LISTS SHADER_STAGE_FILES)
		file(APPEND "${SHADER_STAGE_CONFIG}"
			"list(APPEND SHADER_STAGE_FILES [==[${SOURCE_FILE}]==])\n")
	endforeach()

	add_custom_target(${TARGET_NAME}
		COMMAND ${CMAKE_COMMAND}
			-D "SHADER_STAGE_CONFIG=${SHADER_STAGE_CONFIG}"
			-P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
		COMMENT "Staging merged shader tree"
		VERBATIM
	)
endfunction()

if(CMAKE_SCRIPT_MODE_FILE)
	if(NOT SHADER_STAGE_CONFIG)
		message(FATAL_ERROR "SHADER_STAGE_CONFIG is required")
	endif()
	include("${SHADER_STAGE_CONFIG}")

	macro(register_shader SOURCE_FILE DESTINATION_PATH)
		set(NORMAL_DESTINATION_PATH "${DESTINATION_PATH}")
		cmake_path(NORMAL_PATH NORMAL_DESTINATION_PATH)
		string(TOLOWER "${NORMAL_DESTINATION_PATH}"
			CASE_INSENSITIVE_DESTINATION_PATH)
		string(SHA256 DESTINATION_KEY
			"${CASE_INSENSITIVE_DESTINATION_PATH}")
		if(DEFINED "SHADER_STAGE_SOURCE_${DESTINATION_KEY}")
			message(FATAL_ERROR
				"Shader stage duplicate destination '${NORMAL_DESTINATION_PATH}': "
				"'${SHADER_STAGE_SOURCE_${DESTINATION_KEY}}' and '${SOURCE_FILE}'")
		endif()
		set("SHADER_STAGE_SOURCE_${DESTINATION_KEY}" "${SOURCE_FILE}")
		list(APPEND SHADER_STAGE_SOURCES "${SOURCE_FILE}")
		list(APPEND SHADER_STAGE_DESTINATIONS "${NORMAL_DESTINATION_PATH}")
	endmacro()

	foreach(SOURCE_DIRECTORY IN LISTS SHADER_STAGE_DIRECTORIES)
		file(GLOB_RECURSE DIRECTORY_FILES
			LIST_DIRECTORIES FALSE
			RELATIVE "${SOURCE_DIRECTORY}"
			"${SOURCE_DIRECTORY}/*")
		list(SORT DIRECTORY_FILES)
		foreach(RELATIVE_PATH IN LISTS DIRECTORY_FILES)
			register_shader(
				"${SOURCE_DIRECTORY}/${RELATIVE_PATH}"
				"${RELATIVE_PATH}")
		endforeach()
	endforeach()

	foreach(SOURCE_FILE IN LISTS SHADER_STAGE_FILES)
		cmake_path(GET SOURCE_FILE FILENAME DESTINATION_PATH)
		register_shader("${SOURCE_FILE}" "${DESTINATION_PATH}")
	endforeach()

	file(REMOVE_RECURSE "${SHADER_STAGE_DESTINATION}")
	file(MAKE_DIRECTORY "${SHADER_STAGE_DESTINATION}")

	list(LENGTH SHADER_STAGE_SOURCES SHADER_COUNT)
	if(SHADER_COUNT GREATER 0)
		math(EXPR SHADER_LAST_INDEX "${SHADER_COUNT} - 1")
		foreach(SHADER_INDEX RANGE ${SHADER_LAST_INDEX})
			list(GET SHADER_STAGE_SOURCES ${SHADER_INDEX} SOURCE_FILE)
			list(GET SHADER_STAGE_DESTINATIONS ${SHADER_INDEX}
				DESTINATION_PATH)
			set(STAGED_FILE
				"${SHADER_STAGE_DESTINATION}/${DESTINATION_PATH}")
			cmake_path(GET STAGED_FILE PARENT_PATH STAGED_DIRECTORY)
			file(MAKE_DIRECTORY "${STAGED_DIRECTORY}")
			file(COPY_FILE "${SOURCE_FILE}" "${STAGED_FILE}")
		endforeach()
	endif()
endif()
