import renderdoc as rd

from common import enum_name, format_name, resource_id, result_message, result_ok, safe_get


class CaptureSession(object):
    def __init__(self, path):
        self.path = path
        self.capture = None
        self.controller = None
        self.resources = []
        self.resource_by_id = {}
        self.textures = []
        self.texture_by_id = {}
        self.buffers = []
        self.buffer_by_id = {}
        self._usage = {}
        self.initialized = False

    def open(self):
        rd.InitialiseReplay(rd.GlobalEnvironment(), [])
        self.initialized = True
        self.capture = rd.OpenCaptureFile()
        status = self.capture.OpenFile(self.path, "", None)
        if not result_ok(status):
            raise RuntimeError("Could not open capture: " + result_message(status))
        support = self.capture.LocalReplaySupport()
        if enum_name(support) != "Supported":
            raise RuntimeError("Capture is not locally replayable: " + enum_name(support))
        status, self.controller = self.capture.OpenCapture(rd.ReplayOptions(), None)
        if not result_ok(status) or self.controller is None:
            raise RuntimeError("Could not create replay controller: " + result_message(status))
        self.resources = list(self.controller.GetResources())
        self.resource_by_id = dict((resource_id(item.resourceId), item)
                                   for item in self.resources)
        self.textures = list(self.controller.GetTextures())
        self.texture_by_id = dict((resource_id(item.resourceId), item)
                                  for item in self.textures)
        self.buffers = list(self.controller.GetBuffers())
        self.buffer_by_id = dict((resource_id(item.resourceId), item)
                                 for item in self.buffers)
        return self

    def close(self):
        if self.controller is not None:
            self._usage = {}
            self.resources = []
            self.resource_by_id = {}
            self.textures = []
            self.texture_by_id = {}
            self.buffers = []
            self.buffer_by_id = {}
            self.controller.Shutdown()
            self.controller = None
        if self.capture is not None:
            self.capture.Shutdown()
            self.capture = None
        if self.initialized:
            rd.ShutdownReplay()
            self.initialized = False

    def name(self, rid):
        key = resource_id(rid)
        item = self.resource_by_id.get(key)
        if item is not None and item.name:
            return item.name
        if key == 0:
            return "Null"
        return "ResourceId({})".format(key)

    def app_named_resources(self):
        return [item for item in self.resources
                if not item.autogeneratedName and resource_id(item.resourceId) != 0]

    def resolve_resource(self, query):
        try:
            key = int(str(query), 0)
            if key in self.resource_by_id:
                return key
        except Exception:
            pass
        lowered = str(query).lower()
        exact = [item for item in self.resources if item.name.lower() == lowered]
        if len(exact) == 1:
            return resource_id(exact[0].resourceId)
        partial = [item for item in self.resources if lowered in item.name.lower()]
        if len(partial) == 1:
            return resource_id(partial[0].resourceId)
        if len(partial) > 1:
            names = sorted(item.name for item in partial)[:12]
            raise ValueError("Resource name is ambiguous: " + ", ".join(names))
        raise ValueError("Resource not found: " + str(query))

    def usage(self, rid):
        key = resource_id(rid)
        if key not in self._usage:
            self._usage[key] = list(self.controller.GetUsage(
                self.resource_by_id[key].resourceId))
        return self._usage[key]

    def texture_description(self, rid):
        return self.texture_by_id.get(resource_id(rid))

    def resource_record(self, item):
        rid = resource_id(item.resourceId)
        texture = self.texture_by_id.get(rid)
        buffer_desc = self.buffer_by_id.get(rid)
        record = {
            "resourceId": rid,
            "name": item.name,
            "type": enum_name(item.type),
            "autogeneratedName": bool(item.autogeneratedName),
        }
        if texture is not None:
            record.update({
                "kind": "texture",
                "width": safe_get(texture, "width", 0),
                "height": safe_get(texture, "height", 0),
                "depth": safe_get(texture, "depth", 0),
                "arraySize": safe_get(texture, "arraysize", 0),
                "mips": safe_get(texture, "mips", 0),
                "samples": safe_get(texture, "msSamp", 1),
                "sampleQuality": safe_get(texture, "msQual", 0),
                "format": format_name(safe_get(texture, "format")),
                "dimension": enum_name(safe_get(texture, "dimension", "")),
                "bindFlags": enum_name(safe_get(texture, "creationFlags", "")),
            })
        elif buffer_desc is not None:
            record.update({
                "kind": "buffer",
                "length": safe_get(buffer_desc, "length", 0),
                "creationFlags": enum_name(safe_get(buffer_desc, "creationFlags", "")),
            })
        else:
            record["kind"] = "object"
        return record
